config/routes.rb
Rails.application.routes.draw do

  root to: "home#show"
  get '/client_login' => 'home#client_login'
  get '/dashboard' => 'dashboard#show'
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/auth0/client_callback' => 'auth0#client_callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/sso' => 'auth0#sso'
  get '/auth/logout' => 'auth0#logout'

  resources :users, only: [:new, :create]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  include ApplicationHelper

  def callback
    # OmniAuth places the User Profile information (retrieved by omniauth-auth0) in request.env['omniauth.auth'].
    # In this tutorial, you will store that info in the session, under 'userinfo'.
    # If the id_token is needed, you can get it from session[:userinfo]['credentials']['id_token'].
    # Refer to https://github.com/auth0/omniauth-auth0#auth-hash for complete information on 'omniauth.auth' contents.
    handle_callback(dashboard_path)
  end

  def client_callback
    handle_callback("#{ENV['CLIENT_SITE_URL']}/auth/auth0?connection=Username-Password-Authentication")
  end

  def logout
    if session[:userinfo1].present? then
      session.delete(:userinfo1)
    end
    redirect_to sprintf("https://%s/v2/logout?federated&returnTo=%s",ENV["AUTH0_DOMAIN"],root_url)  
  end

  def sso
    if request.params['target_url'].present? then
      # should actually constrain this to make sure it is a local redirect?  Or only expected redirects.
    else
      redirect_to 'auth/failure?message=target_url is required for this endpoint'
      return
    end
    if not request.params['connection'].present? then
      redirect_to 'auth/failure?message=connection is required for this endpoint'
      return
    end

    if session[:userinfo1].present? then
      # User is already logged in, just redirect
      redirect_to params['target_url']
    else 
      session[:target_url] = request.params['target_url']
      # Redirect to login 
      redirect_to getAuthUrl(connection: request.params['connection'])
    end
  end

  # if user authentication fails on the provider side OmniAuth will redirect to /auth/failure,
  # passing the error message in the 'message' request param.
  def failure
    @error_msg = request.params['message']
  end

  private

  def handle_callback(redirectUrl)
    session[:userinfo1] = request.env['omniauth.auth']

    if session[:target_url].present? then
      redirect_to session[:target_url]
      session.delete(:target_url)
    else
      redirect_to redirectUrl
    end
  end
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern
  include ApplicationHelper

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
  	puts "====#{session[:userinfo1].inspect}======="
    redirect_to getAuthUrl() unless session[:userinfo1].present?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
 include Secured

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def client_login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'uri'
	require 'net/http'

	def new
	end

  def create
  	url = URI("https://techplus.auth0.com/dbconnections/signup")
  	http = Net::HTTP.new(url.host, url.port)
		http.use_ssl = true
		http.verify_mode = OpenSSL::SSL::VERIFY_NONE

		request = Net::HTTP::Post.new(url)
		request["content-type"] = 'application/json'
		request.body = "{\"client_id\": \"4SgNl8rEj5tLnSxyGyJwTQqiuxsoKcSU\",\"email\": \"#{params['user']['email']}\",\"password\": \"#{params['user']['password']}\",\"user_metadata\": {\"role\": \"#{params['user']['role']}\"}}"
		response = http.request(request)
		puts response.read_body
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def getAuthUrl(connection: 'Username-Password-Authentication')
    return sprintf("#{ENV['RELATIVE_URL']}/auth/auth0?connection=%s",connection)
  end

  def current_user
  	user_data = JSON.parse(session[:userinfo1].to_json)["extra"]["raw_info"]
  	return {
  		email: user_data["email"],
  		full_name: user_data["user_metadata"]["full_name"],
  		role: user_data["user_metadata"]["Role"]
  	}
  end

  def is_logged_in?
    if session[:userinfo1].present?
      true
    else
      false
    end
  end

  def get_user_target_url
    if current_user[:role] == 'super_admin'
      return '/users/super_admin'
    elsif current_user[:role] == 'admin'
      return '/users/admin'
    elsif current_user[:role] == 'manager'
      return '/users/manager'
    elsif current_user[:role] == 'developer'
      return '/users/developer'
    end
  end

  def get_user_target_url_with_relative_url
    return ENV['RELATIVE_URL'] + get_user_target_url
  end
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auth0/failure.html.erb
<div class="panel panel-danger">
  <h2>Error <%= @error_msg %></h2>
  <p><%= @omniauth_error %></p>
</div>

app/views/dashboard/show.html.erb
<section class="jumbotron  text-center">
  <h2>Hello  <%= current_user[:role] + " " + current_user[:full_name] %></h2>
  <h4>You are in :) Login app</h4>
  <a class="btn btn-success btn-lg" href="<%= ENV['CLIENT_SITE_URL'] %>/auth/sso?connection=Username-Password-Authentication&target_url=<%= get_user_target_url_with_relative_url %>">Open App2</a>
  <a class="btn btn-success btn-lg" href="auth/logout">Logout</a>
</section>

app/views/home/client_login.html.erb
<section class="jumbotron text-center">
  <h1>Client Login</h1>
  <% unless is_logged_in? %>
	  <a class="btn btn-success btn-lg" onclick="client_signin()">Login / Signup</a>
  <% end %>
</section>

app/views/home/show.html.erb
<section class="jumbotron text-center">
  <h1>Login app</h1>
  <% unless is_logged_in? %>
	  <a class="btn btn-success btn-lg" onclick="signin()">Login / Signup</a>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if Rails.env.production? %>
    <base href="/ror/sso_login/" />
  <% else %>
    <base href="/" />
  <% end %>
  <%= yield :cdn_code %>
  <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag '//cdn.auth0.com/js/lock/10.0.0/lock.min.js' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">My Application</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if params[:controller] == 'home' && params[:action] == 'show' %>"><%= link_to "Login", root_path %></li>
            <li class="<%= 'active' if params[:controller] == 'home' && params[:action] == 'client_login' %>"><%= link_to "Client Login", client_login_path %></li>
            <li class="<%= 'active' if params[:controller] == 'dashboard' %>"><%= link_to 'My Dashboard', dashboard_path %></li>
          </ul>
        </div>
      </div>
    </nav>
 <div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_tag users_path do %>
  <fieldset>
    <legend>Sign up</legend>
    <p>
      <%= label_tag :email %>
      <%= text_field_tag "user[email]", nil, placeholder: "Email", required: true %>
    </p>
    <p>
      <%= label_tag :password %>
      <%= password_field_tag "user[password]", nil, placeholder: "Password", required: true %>
    </p>
    <p>
      <%= label_tag :role %>
      <%= select_tag "user[role]", options_for_select([ "Manager", "Developer" ]), required: true %>
    </p>
    <%= submit_tag "Sign in", class: "btn btn-large btn-primary" %>
  </fieldset>
<% end %>